#!/bin/bash

export DISPLAY=$DISPLAY
export WAYLAND_DISPLAY=$WAYLAND_DISPLAY
export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
export XAUTHORITY=$XAUTHORITY
export DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS
export GTK_THEME=Adwaita:dark

exec /usr/bin/gparted
